name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm

      - name: Install dependencies with PDM
        run: |
          pdm install -v

      - name: Lint with Ruff
        run: |
          pdm run ruff src/
          pdm run ruff tests/

      - name: Run tests
        run: |
          pdm run pytest tests/
